openapi: 3.0.0
info:
  title: Dad Jokes Demo API
  version: 0.0.1
  description: A simple API that just provides some humour
servers:
  - url: https://api.kong.lan
paths:
  /dadjokes:
    get:
      summary: Show a Dad Joke
      description: Returns possibly one of the funniest jokes you have ever heard.
      tags:
        - jokes
      responses:
        '200':
          description: A very funny joke

  /auth/dadjokes:
    get:
      summary: Show a Dad Joke with authentication
      description: Returns possibly one of the funniest jokes you have ever heard.
      security:
        - ApiKeyAuth: []
        - basicAuth: []
        - oAuth2ClientCredentials: []
      tags:
        - jokes
      responses:
        '200':
          description: A very funny joke

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: Pass an apikey from the 'jokes' ACL for authentication
      in: header
      name: apikey
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: https://api.kong.lan:18443/auth/realms/kong/protocol/openid-connect/token
          scopes: {} # Getty Images does not use scopes

tags:
  - name: jokes
    description: API providing some poor puns

