version: '2.1'

networks:
  case-kong-net:
    name: case-kong-net
    driver: bridge

services:
  db:
    networks:
      - case-kong-net
    image: postgres:9.5
    container_name: case-kong-db
    environment:
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true

  ad-server:
    networks:
      - case-kong-net
    container_name: case-ad-server
    image: nginx:1.17.3-alpine
    volumes:
      - ./ldap-server:/setup-ad/
    # run as privileged to workaround this issue
    # set_nt_acl_no_snum: fset_nt_acl returned NT_STATUS_ACCESS_DENIED
    privileged: true
    ports:
      - "389:389/tcp"

  httpbin-1:
    networks:
      - case-kong-net
    container_name: case-httpbin-1
    image: "kennethreitz/httpbin"
#    ports:
#      - "80:80/tcp"

  httpbin-2:
    networks:
      - case-kong-net
    container_name: case-httpbin-2
    image: "kennethreitz/httpbin"
#    ports:
#      - "80:80/tcp"

  keycloak:
    networks:
      - case-kong-net
    container_name: case-keycloak
    image: jboss/keycloak:9.0.0
    volumes:
      - ./kong-realm.json:/tmp/kong-realm.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/kong-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "8080:8080/tcp"
      - "8443:8443/tcp"

  redis:
    networks:
      - case-kong-net
    container_name: case-redis
    image: redis:latest
#    ports:
#      - "6379:6379/tcp"

  zipkin:
    networks:
      - case-kong-net
    container_name: case-zipkin
    image: openzipkin/zipkin
#    ports:
#      - "9411:9411/tcp"

  vault:
    networks:
      - case-kong-net
    container_name: case-vault
    image: vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
#    ports:
#      - "8200:8200/tcp"


  ha-proxy:
    networks:
      - case-kong-net
    container_name: case-ha-proxy
    image: haproxy:2.2.4-alpine
    volumes:
      - /home/stu/kongpose/ha-proxy:/usr/local/etc/haproxy:ro
    ports:
      - "8888:8888/tcp"
      - "8404:8404/tcp"
      - "9999:9999/tcp"

