_format_version: "1.1"
_workspace: debian
services:
- connect_timeout: 60000
  host: status-upstream
  name: Healthcheck
  path: /status
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: Healthcheck
    paths:
    - /health
    path_handling: v1
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
  plugins:
  - name: request-transformer
    config:
      add:
        body: []
        headers:
        - kong-admin-token:password
        querystring: []
      append:
        body: []
        headers: []
        querystring: []
      http_method: null
      remove:
        body: []
        headers: []
        querystring: []
      rename:
        body: []
        headers: []
        querystring: []
      replace:
        body: []
        headers: []
        querystring: []
        uri: null
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https
- connect_timeout: 60000
  host: httpbin-1
  name: local_httpbin
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: localhttpbin
    paths:
    - /httpbin
    path_handling: v0
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
upstreams:
- name: status-upstream
  algorithm: round-robin
  slots: 10000
  healthchecks:
    active:
      concurrency: 10
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 0
        successes: 0
      http_path: /
      https_verify_certificate: true
      type: http
      timeout: 1
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        tcp_failures: 0
        timeouts: 0
        interval: 0
    passive:
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 0
      type: http
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 500
        - 503
        tcp_failures: 0
        timeouts: 0
  hash_on: none
  hash_fallback: none
  hash_on_cookie_path: /
  targets:
  - target: kong:48001
    weight: 100
