# my global config
global:
  external_labels:
    monitor: 'kong-project'

rule_files:

scrape_configs:
  - job_name: 'vitals_statsd_exporter'
    scrape_interval: "5s"
    static_configs:
      - targets: ['kongpose_statsd-exporter_1:9102']
  - job_name: 'kong_exporter'
    scrape_interval: "5s"
    static_configs:
      - targets: ['kongpose_kong-dp_1:48000']
