#!/usr/bin/env bash
#
# Regenerate the Kong demo certificate hierarchy using smallstep's step-cli.
#
# Generates everything kongpose actually consumes:
#   - root_ca.pem / .key             (self-signed)
#   - intermediate_ca1.pem / .key    (signed by root)
#   - intermediate_ca2.pem / .key    (signed by int1)
#   - kong.lan.pem / .key            (CN=manager.kong.lan + SANs for admin/portal/api/proxy)
#   - wild.kong.lan.pem / .key       (CN=*.kong.lan — used by keycloak, solace)
#   - client.kong.lan.pem / .key     (mTLS client cert)
#   - client/mtls-consumer.kong.lan.pem / .key  (mTLS consumer cert)
#   - combined-wild.pem              (chain bundle for HAproxy)
#   - ../hybrid/cluster.crt / .key   (self-signed EC P-384 cert for Kong CP↔DP hybrid mode)
#
# Renewal logic: kong.lan.pem and ../hybrid/cluster.crt are checked independently. If
# either is within GRACE_DAYS of expiry, the affected cert set is regenerated.
# Intermediate CAs are checked individually so they only rotate when actually near expiry.
#
# Run from anywhere — the script self-locates to ssl-certs/smallstep/.

set -euo pipefail

cd "$(dirname "$0")"

# ──────────────── Configuration ────────────────

STEP_IMAGE="smallstep/step-cli:0.28.6"   # pin for reproducibility; bump deliberately

GRACE_DAYS=30                            # treat anything expiring within N days as "needs renewal"
MAX_BACKUP_KEEP=3                        # keep this many ../.cert-backup-* dirs; older ones get pruned

# step-cli's --not-after uses Go duration syntax (h/m/s only — no "d"), so express in hours.
ROOT_CA_HOURS=87600                       # 10y (3650d)
INT1_CA_HOURS=43800                       # 5y  (1825d)
INT2_CA_HOURS=26280                       # 3y  (1095d)
LEAF_HOURS=8760                           # 1y  (365d)

# Hybrid CP/DP cluster cert is generated by openssl (not step), which uses -days.
HYBRID_CERT_DAYS=1095                     # 3y — matches what `kong hybrid gen_cert` produces.

# Domains to cover. The first one is the "primary" (used for CNs); every domain
# listed here is added to the SAN list of the primary and wildcard certs, so a
# single cert serves all of them.
DOMAINS=(kong.lan kong.com)

# Subdomain prefixes the kong.lan-style leaf cert serves on (per domain).
KONG_PREFIXES=(manager api portal portal-api proxy)

# Extra SANs attached to every leaf cert. step-cli auto-detects DNS vs IP.
EXTRA_SANS=(127.0.0.1)

# Build the primary CN + SAN list from the configuration above.
PRIMARY_CN="${KONG_PREFIXES[0]}.${DOMAINS[0]}"

PRIMARY_SANS=()
for domain in "${DOMAINS[@]}"; do
    for prefix in "${KONG_PREFIXES[@]}"; do
        PRIMARY_SANS+=("${prefix}.${domain}")
    done
    PRIMARY_SANS+=("$domain")
done
PRIMARY_SANS+=("${EXTRA_SANS[@]}")

# ──────────────── Pre-flight ────────────────

command -v docker  >/dev/null || { echo "ERROR: docker not found"; exit 1; }
command -v openssl >/dev/null || { echo "ERROR: openssl not found (needed for expiry check)"; exit 1; }

HOST_UID=$(id -u)
HOST_GID=$(id -g)

run_step() {
    docker run --rm \
        --user "${HOST_UID}:${HOST_GID}" \
        -v "$PWD:/app" \
        -w /app \
        "$STEP_IMAGE" "$@"
}

# Refresh macOS trust stores for the demo root CA.
# Login keychain is always attempted; system keychain is updated only if writable
# or passwordless sudo is available.
refresh_macos_root_trust() {
    [[ "$OSTYPE" == darwin* ]] || return 0

    local cert_name="Demo Kong Root CA"
    local cert_path="root_ca.pem"
    local login_keychain="$HOME/Library/Keychains/login.keychain-db"
    local system_keychain="/Library/Keychains/System.keychain"

    if [[ ! -f "$cert_path" ]]; then
        echo "    macOS trust refresh skipped: $cert_path not found"
        return 0
    fi

    echo "==> macOS trust: refreshing '$cert_name' in login keychain"
    security delete-certificate -c "$cert_name" "$login_keychain" >/dev/null 2>&1 || true
    security add-trusted-cert -r trustRoot -k "$login_keychain" "$cert_path"

    if [[ -w "$system_keychain" ]]; then
        echo "==> macOS trust: refreshing '$cert_name' in system keychain"
        security delete-certificate -c "$cert_name" "$system_keychain" >/dev/null 2>&1 || true
        security add-trusted-cert -d -r trustRoot -k "$system_keychain" "$cert_path"
    elif command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
        echo "==> macOS trust: refreshing '$cert_name' in system keychain (sudo -n)"
        sudo security delete-certificate -c "$cert_name" "$system_keychain" >/dev/null 2>&1 || true
        sudo security add-trusted-cert -d -r trustRoot -k "$system_keychain" "$cert_path"
    else
        echo "    system keychain not updated (needs sudo). Run manually if desired:"
        echo "    sudo security delete-certificate -c '$cert_name' $system_keychain"
        echo "    sudo security add-trusted-cert -d -r trustRoot -k $system_keychain ssl-certs/smallstep/$cert_path"
    fi
}

# Returns 0 if file is missing or will expire within GRACE_DAYS, 1 otherwise.
needs_renewal() {
    local file="$1"
    if [[ ! -f "$file" ]]; then
        return 0
    fi
    local seconds=$((GRACE_DAYS * 24 * 60 * 60))
    if openssl x509 -in "$file" -checkend "$seconds" -noout &>/dev/null; then
        return 1
    fi
    return 0
}

# Sync the ca_certificates and certificates blocks of deck/default-entities.yaml
# with the on-disk PEM/key files. Match is by tag. Idempotent.
update_deck_certs() {
    local deck_file="../../deck/default-entities.yaml"
    if [[ ! -f "$deck_file" ]]; then
        return
    fi
    if ! command -v yq >/dev/null; then
        echo "    yq not installed — skipping deck/default-entities.yaml update"
        echo "    (install: snap install yq, brew install yq, or github.com/mikefarah/yq)"
        return
    fi

    local updated=()
    local pair tag cert_file key_file triple

    # ca_certificates: tag → cert PEM file (cert only)
    for pair in "root-ca:root_ca.pem" "intermediate_ca1:intermediate_ca1.pem" "intermediate_ca2:intermediate_ca2.pem"; do
        tag="${pair%%:*}"
        cert_file="${pair##*:}"
        [[ -f "$cert_file" ]] || continue
        tag="$tag" cert_content="$(cat "$cert_file")" yq -i \
            '(.ca_certificates[] | select(.tags[] == strenv(tag))).cert = strenv(cert_content)' \
            "$deck_file"
        updated+=("ca:$tag")
    done

    # Strip stale cert_digest from all ca_certificates entries — Kong recomputes
    # it server-side on sync, and keeping the literal value in the YAML just
    # creates drift whenever the cert is rotated.
    yq -i 'del(.ca_certificates[].cert_digest)' "$deck_file"

    # The legacy mtls-consumer cert was created untagged. Tag it (one-time,
    # identified by its stable id) so the loop below can address it by tag.
    yq -i '(.certificates[] | select(.id == "f3ae1bb2-ea6a-4caf-a7a7-2f078b7842db") | select(.tags == null)).tags = ["mtls-consumer"]' "$deck_file"

    # certificates: tag → cert+key pair.
    # - proxy.kong.lan uses kong.lan.* (proxy.kong.lan is a SAN on that cert)
    # - mtls-consumer uses the dedicated mTLS client identity cert
    for triple in \
        "proxy.kong.lan:kong.lan.pem:kong.lan.key" \
        "mtls-consumer:client/mtls-consumer.kong.lan.pem:client/mtls-consumer.kong.lan.key"
    do
        IFS=':' read -r tag cert_file key_file <<< "$triple"
        [[ -f "$cert_file" && -f "$key_file" ]] || continue
        tag="$tag" cert_content="$(cat "$cert_file")" key_content="$(cat "$key_file")" yq -i \
            '(.certificates[] | select(.tags[] == strenv(tag))) |= (.cert = strenv(cert_content) | .key = strenv(key_content))' \
            "$deck_file"
        updated+=("cert:$tag")
    done

    if (( ${#updated[@]} > 0 )); then
        echo "==> synced deck/default-entities.yaml: ${updated[*]}"
    fi
}

# Delete oldest ../.cert-backup-* dirs beyond MAX_BACKUP_KEEP. Names are
# .cert-backup-YYYYMMDD_HHMMSS, so lexicographic sort == chronological.
prune_old_backups() {
    shopt -s nullglob
    local backups=(../.cert-backup-*)
    shopt -u nullglob
    if (( ${#backups[@]} <= MAX_BACKUP_KEEP )); then
        return
    fi
    local sorted=()
    local line
    while IFS= read -r line; do
        sorted+=("$line")
    done < <(printf '%s\n' "${backups[@]}" | sort)
    local to_delete=$(( ${#sorted[@]} - MAX_BACKUP_KEEP ))
    local i
    for ((i=0; i<to_delete; i++)); do
        rm -rf "${sorted[$i]}"
        echo "    pruned old backup: $(basename "${sorted[$i]}")"
    done
}

# ──────────────── Decide if renewal is needed ────────────────
# Renewal is gated, but the deck/backup-pruning housekeeping below always runs
# so a no-op invocation still keeps the deck file in sync and trims old backups.

RENEWAL_NEEDED=false
SMALLSTEP_NEEDED=false
HYBRID_NEEDED=false

if needs_renewal kong.lan.pem; then
    SMALLSTEP_NEEDED=true
    RENEWAL_NEEDED=true
    echo "==> kong.lan.pem missing or near expiry — will regenerate smallstep CA chain + leaves"
else
    expiry=$(openssl x509 -in kong.lan.pem -enddate -noout | cut -d= -f2)
    echo "kong.lan.pem is valid until $expiry (more than ${GRACE_DAYS}d away). Skipping smallstep regeneration."
fi

if needs_renewal ../hybrid/cluster.crt; then
    HYBRID_NEEDED=true
    RENEWAL_NEEDED=true
    echo "==> ../hybrid/cluster.crt missing or near expiry — will regenerate hybrid CP/DP cert"
else
    expiry=$(openssl x509 -in ../hybrid/cluster.crt -enddate -noout | cut -d= -f2)
    echo "../hybrid/cluster.crt is valid until $expiry (more than ${GRACE_DAYS}d away). Skipping hybrid regeneration."
fi

if $RENEWAL_NEEDED; then

# ──────────────── Backup ────────────────

BACKUP_DIR="../.cert-backup-$(date +%Y%m%d_%H%M%S)"
mkdir -p "$BACKUP_DIR"
shopt -s nullglob
if $SMALLSTEP_NEEDED; then
    backup_files=(*.pem *.key client/*.pem client/*.key)
    if (( ${#backup_files[@]} > 0 )); then
        cp -p "${backup_files[@]}" "$BACKUP_DIR/" 2>/dev/null || true
        echo "    backed up smallstep certs to $BACKUP_DIR"
    fi
fi
if $HYBRID_NEEDED; then
    hybrid_files=(../hybrid/cluster.crt ../hybrid/cluster.key)
    if (( ${#hybrid_files[@]} > 0 )); then
        mkdir -p "$BACKUP_DIR/hybrid"
        cp -p "${hybrid_files[@]}" "$BACKUP_DIR/hybrid/" 2>/dev/null || true
        echo "    backed up hybrid certs to $BACKUP_DIR/hybrid"
    fi
fi
shopt -u nullglob

if $SMALLSTEP_NEEDED; then

ROOT_CA_ROTATED=false

# ──────────────── Templates ────────────────
# Step CLI templates that pin maxPathLen for the 3-level CA hierarchy.
# Without these, intermediate2 may not be permitted to sign leaves.

write_template_if_missing() {
    local path="$1" body="$2"
    if [[ ! -f "$path" ]]; then
        printf '%s\n' "$body" > "$path"
        echo "    wrote template $path"
    fi
}

# Build root.tpl dynamically so its nameConstraints stay in sync with $DOMAINS.
# nameConstraints (critical) limits the entire chain to issue certs only for
# the listed DNS suffixes and IP ranges — even if root_ca.pem is imported into
# an OS truststore, it can't be abused to sign for arbitrary domains.
write_root_template() {
    local permitted_dns="" first=1
    for d in "${DOMAINS[@]}"; do
        if (( first )); then permitted_dns="\"$d\""; first=0
        else permitted_dns="$permitted_dns, \"$d\""
        fi
    done

    local new_content
    new_content=$(cat <<EOF
{
    "subject": {{ toJson .Subject }},
    "issuer": {{ toJson .Subject }},
    "keyUsage": ["certSign", "crlSign"],
    "basicConstraints": {
        "isCA": true,
        "maxPathLen": 2
    },
    "nameConstraints": {
        "critical": true,
        "permittedDNSDomains": [${permitted_dns}],
        "permittedIPRanges": ["127.0.0.0/8", "::1/128"]
    }
}
EOF
)

    if [[ -f root.tpl ]] && [[ "$(cat root.tpl)" == "$new_content" ]]; then
        return
    fi

    if [[ -f root_ca.pem ]]; then
        echo "    WARNING: root.tpl changed (DOMAINS updated?) — existing root_ca.pem"
        echo "             does NOT reflect new constraints. Delete root_ca.pem (and"
        echo "             the intermediate CAs) and re-run to regenerate the chain."
    fi

    printf '%s\n' "$new_content" > root.tpl
    echo "    wrote root.tpl with nameConstraints for: ${DOMAINS[*]}"
}

write_root_template

write_template_if_missing intermediate1.tpl '{
    "subject": {{ toJson .Subject }},
    "keyUsage": ["certSign", "crlSign"],
    "basicConstraints": {
        "isCA": true,
        "maxPathLen": 1
    }
}'

write_template_if_missing intermediate2.tpl '{
    "subject": {{ toJson .Subject }},
    "keyUsage": ["certSign", "crlSign"],
    "basicConstraints": {
        "isCA": true,
        "maxPathLen": 0
    }
}'

# ──────────────── CA hierarchy ────────────────

if needs_renewal root_ca.pem; then
    echo "==> generating Root CA"
    run_step step certificate create "Demo Kong Root CA" \
        /app/root_ca.pem /app/root_ca.key \
        --template /app/root.tpl \
        --not-after "${ROOT_CA_HOURS}h" \
        --no-password --insecure --force
    ROOT_CA_ROTATED=true
fi

if needs_renewal intermediate_ca1.pem; then
    echo "==> generating Intermediate CA 1"
    run_step step certificate create "Demo Kong Intermediate1 CA" \
        /app/intermediate_ca1.pem /app/intermediate_ca1.key \
        --template /app/intermediate1.tpl \
        --ca /app/root_ca.pem --ca-key /app/root_ca.key \
        --not-after "${INT1_CA_HOURS}h" \
        --no-password --insecure --force
fi

if needs_renewal intermediate_ca2.pem; then
    echo "==> generating Intermediate CA 2"
    run_step step certificate create "Demo Kong Intermediate2 CA" \
        /app/intermediate_ca2.pem /app/intermediate_ca2.key \
        --template /app/intermediate2.tpl \
        --ca /app/intermediate_ca1.pem --ca-key /app/intermediate_ca1.key \
        --not-after "${INT2_CA_HOURS}h" \
        --no-password --insecure --force
fi

# ──────────────── Leaf certs ────────────────

# Generate a leaf signed by Intermediate CA 2.
# The CN is auto-included as a SAN (modern TLS clients ignore CN and only
# match against SANs). Duplicate SANs are de-duped so callers can pass the
# CN explicitly without producing a bad cert.
# Args: <cn> <cert-path> <key-path> [san1 san2 ...]
generate_leaf() {
    local cn="$1" cert_path="$2" key_path="$3"
    shift 3

    local unique_sans=()
    local s existing found i
    for s in "$cn" "$@"; do
        found=0
        # Index-based loop avoids empty-array expansion issues with `set -u`.
        for ((i=0; i<${#unique_sans[@]}; i++)); do
            existing="${unique_sans[i]}"
            [[ "$existing" == "$s" ]] && { found=1; break; }
        done
        [[ $found -eq 0 ]] && unique_sans+=("$s")
    done

    local args=(
        "$cn"
        "/app/$cert_path"
        "/app/$key_path"
        --profile leaf
        --ca /app/intermediate_ca2.pem
        --ca-key /app/intermediate_ca2.key
        --not-after "${LEAF_HOURS}h"
        --no-password --insecure --force
    )
    for ((i=0; i<${#unique_sans[@]}; i++)); do
        args+=(--san "${unique_sans[i]}")
    done
    run_step step certificate create "${args[@]}"
}

echo "==> generating kong.lan.* (Admin/Manager/Portal/Proxy)"
generate_leaf "$PRIMARY_CN" kong.lan.pem kong.lan.key "${PRIMARY_SANS[@]}"

echo "==> generating wild.kong.lan.* (wildcard, used by keycloak/solace)"
WILDCARD_SANS=()
for domain in "${DOMAINS[@]}"; do
    WILDCARD_SANS+=("*.${domain}")
done
WILDCARD_SANS+=("${EXTRA_SANS[@]}")
generate_leaf "*.${DOMAINS[0]}" wild.kong.lan.pem wild.kong.lan.key "${WILDCARD_SANS[@]}"

echo "==> generating client.kong.lan.* (mTLS client)"
generate_leaf "client.${DOMAINS[0]}" client.kong.lan.pem client.kong.lan.key "${EXTRA_SANS[@]}"

echo "==> generating client/mtls-consumer.kong.lan.* (mTLS consumer)"
mkdir -p client
generate_leaf "mtls-consumer" client/mtls-consumer.kong.lan.pem client/mtls-consumer.kong.lan.key "${EXTRA_SANS[@]}"

# ──────────────── HAproxy bundle ────────────────

echo "==> building combined-wild.pem for HAproxy"
cat wild.kong.lan.pem intermediate_ca2.pem intermediate_ca1.pem root_ca.pem wild.kong.lan.key \
    > combined-wild.pem

# ──────────────── Permissions ────────────────
# step writes keys at 0600. Kong runs as non-root inside the container and the host
# uid differs from the container uid, so the simplest portable fix is world-readable
# 0644 on these demo files. See README.md "HACK Alert" — this is dev-only.

chmod 644 *.pem *.key
if compgen -G "client/*" > /dev/null; then
    chmod 644 client/*.pem client/*.key
fi

if $ROOT_CA_ROTATED; then
    refresh_macos_root_trust
fi

fi  # end SMALLSTEP_NEEDED block

# ──────────────── Hybrid CP/DP cluster cert ────────────────
# Self-signed EC P-384 cert used as both CA and identity for Kong control-plane
# ↔ data-plane mTLS in hybrid mode. Equivalent to `kong hybrid gen_cert` but
# generated on the host so the files end up owned by the current user (no
# `chown` dance after a root-in-container run). See ../hybrid/README.md.

if $HYBRID_NEEDED; then
    echo "==> generating ../hybrid/cluster.{crt,key}"
    mkdir -p ../hybrid
    openssl req -new -x509 -nodes \
        -newkey ec:<(openssl ecparam -name secp384r1) \
        -keyout ../hybrid/cluster.key \
        -out ../hybrid/cluster.crt \
        -days "$HYBRID_CERT_DAYS" \
        -subj "/CN=kong_clustering"
    # 0644 so the non-root kong user inside the container can read the key.
    chmod 644 ../hybrid/cluster.crt ../hybrid/cluster.key
fi

fi  # end RENEWAL_NEEDED block

# ──────────────── Housekeeping (always runs) ────────────────

update_deck_certs
prune_old_backups

# ──────────────── Summary ────────────────

if $RENEWAL_NEEDED; then
    echo ""
    echo "Renewal complete."

    if $SMALLSTEP_NEEDED; then
        echo ""
        echo "Smallstep files:"
        ls -lh root_ca.pem intermediate_ca1.pem intermediate_ca2.pem \
               kong.lan.pem kong.lan.key \
               wild.kong.lan.pem wild.kong.lan.key \
               client.kong.lan.pem client.kong.lan.key \
               combined-wild.pem 2>/dev/null
        if [[ -d client ]]; then
            ls -lh client/*.pem client/*.key 2>/dev/null || true
        fi
        leaf_expiry=$(openssl x509 -in kong.lan.pem -enddate -noout | cut -d= -f2)
        echo "kong.lan leaf expires: $leaf_expiry"
    fi

    if $HYBRID_NEEDED; then
        echo ""
        echo "Hybrid CP/DP files:"
        ls -lh ../hybrid/cluster.crt ../hybrid/cluster.key 2>/dev/null
        hybrid_expiry=$(openssl x509 -in ../hybrid/cluster.crt -enddate -noout | cut -d= -f2)
        echo "hybrid cluster cert expires: $hybrid_expiry"
    fi

    echo ""
    echo "Backup of previous certs: $BACKUP_DIR"
fi

# ──────────────── Restart cert-consuming containers (only if certs changed) ─

if $RENEWAL_NEEDED; then
    # Restart only services that are actually running so we don't error on stopped
    # profile-gated ones (keycloak, solace).
    CERT_CONSUMERS=(kong-cp kong-dp ha-proxy keycloak solace)
    running_consumers=()
    if running_list=$(cd ../.. && docker compose ps --services --status running 2>/dev/null); then
        for svc in "${CERT_CONSUMERS[@]}"; do
            if grep -qxF "$svc" <<<"$running_list"; then
                running_consumers+=("$svc")
            fi
        done
    fi

    if (( ${#running_consumers[@]} == 0 )); then
        echo ""
        echo "No cert-consuming services are currently running. Start the stack with 'docker compose up'."
    elif [[ -t 0 ]]; then
        echo ""
        read -rp "Restart [${running_consumers[*]}] to pick up new certs? [Y/n] " answer
        answer="${answer:-Y}"
        if [[ "$answer" =~ ^[Yy] ]]; then
            (cd ../.. && docker compose restart "${running_consumers[@]}")
        else
            echo "Skipped. Restart manually with: docker compose restart ${running_consumers[*]}"
        fi
    else
        echo ""
        echo "Non-interactive shell; skipping auto-restart. Run manually:"
        echo "    docker compose restart ${running_consumers[*]}"
    fi
fi

echo ""
echo "Don't forget: your OS/browser must trust root_ca.pem (see ssl-certs/README.md)."
